delayTime: 1
ipPattern: (\d+\.\d+\.\d+\.\d+)
lightStates:
  allOff: {'on': false}
  allOn: {bri: 50, ct: 250, 'on': true, sat: 255, transitiontime: 2}
  green:
    bri: 100
    'on': true
    sat: 255
    transitiontime: 4
    xy: [0.5, 0.8]
  noConnect: {bri: 150, effect: colorloop, 'on': true, sat: 255, transitiontime: 4}
  orange:
    bri: 150
    'on': true
    sat: 255
    transitiontime: 4
    xy: [0.6, 0.4]
  red:
    bri: 150
    'on': true
    sat: 255
    transitiontime: 4
    xy: [0.8, 0.3]
  redAlert:
    alert: lselect
    bri: 150
    'on': true
    sat: 255
    transitiontime: 4
    xy: [0.8, 0.3]
  white: {bri: 50, ct: 200, 'on': true, sat: 255, transitiontime: 2}
  yellow:
    bri: 150
    'on': true
    sat: 255
    transitiontime: 4
    xy: [0.55, 0.46]
manualBridgeIP: null
maxDisconnectTime: 15
userName: ositechsupport
